# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-26 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_auto_20200126_1048'),
        ('crm', '0002_auto_20200126_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.User'),
        ),
    ]
