# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-15 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='weight',
            field=models.IntegerField(default=0, max_length=32),
        ),
    ]
