# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-15 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_menu_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
