# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-26 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_auto_20200126_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=128, verbose_name='权限'),
        ),
    ]
